services:
  # Production
  demo-prod:
    image: ghcr.io/${GITHUB_USERNAME}/true-zero-downtime-blueprint:${DEPLOY_ENV:-production}
    pull_policy: always
    restart: always
    environment:
      - DEPLOY_VERSION=${DEPLOY_VERSION:-1}
    networks:
      - web-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-public"
      - "traefik.http.routers.demoprod.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.demoprod.entrypoints=web"
      - "traefik.http.services.demoprod.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=false"

  # Staging
  demo-test:
    image: ghcr.io/${GITHUB_USERNAME}/true-zero-downtime-blueprint:staging
    pull_policy: always
    restart: always
    networks:
      - web-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-public"
      - "traefik.http.routers.demotest.rule=Host(`${TEST_DOMAIN_NAME}`)"
      - "traefik.http.routers.demotest.entrypoints=web"
      - "traefik.http.services.demotest.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  web-public:
    external: true
